# permissions for end users to view helloers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: helloer-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator101
    app.kubernetes.io/part-of: operator101
    app.kubernetes.io/managed-by: kustomize
  name: helloer-viewer-role
rules:
- apiGroups:
  - hello.parham.home
  resources:
  - helloers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hello.parham.home
  resources:
  - helloers/status
  verbs:
  - get
